### ISSUE TITLE
Embedded scripts url?

### ISSUE THREAD

**Issue by levipadre** [schickling/gulp-webserver#105]
Hi,
I'm using this configuration:

```
gulp.task('webserver', function() {
    gulp.src('app')
        .pipe(webserver({
            livereload: true,
            port: 12345,
            directoryListing: false,
            open: true,
            fallback: 'index.html'
        }));
});
```

The werbserver is working, but I need to add some js files to my index.html, and the scripts live outside the app folder (e.g. bower_components, dist).
How can I add these files? E.g:
`<script src="/bower_components/angular/angular.min.js"></script>`

Thanks

**Comment by levipadre** [comment]
Does anybody know about this configuration?

**Comment by tfrijsewijk** [comment]
You can't. You have to start the webserver from the root of your project (`gulp.src('.')`), and go from there: Navigate your browser to `localhost:12345/app` and `src="../bower_components/..."`.

**Comment by levipadre** [comment]
Thank you, this helped a lot, perfect!
