### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by jwstegemann** [schickling/gulp-webserver#21]
I have the requirement to proxy requests to certain URLs to another URL to avoid CORS-problems during development.

I thought it would be great to add this to your config:

```
.pipe(webserver({
      host: "0.0.0.0",
      port: 9000,
      livereload: true,
      proxies: [{
        source: '/abc',
        target: 'http://localhost:8080/abc'
      },
      {
        source: '/def',
        target: 'http://localhost:8080/xyz'
      }]
}));
```

and your requests are being proxied.

**Comment by ajbogh** [comment]
Please note that in order to use a proxy target that has a self-signed cert, you should add this line in the gulpfile.js file before creating the webserver.

    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

**Comment by schickling** [comment]
Thanks @ajbogh for pointing that out!
