### ISSUE TITLE
Cannot get proxy working

### ISSUE THREAD

**Issue by MikaAK** [schickling/gulp-webserver#47]
I'm trying to get webserver to proxy to my api on port 8888 which is originally run on vagrant. 

The api currently runs on a vagrant machine that forwards to port 8888 locally. 
My gulp tasks looks like this

``` javascript
gulp.task('serve', ['watch'], function() {
  gulp.src(['.tmp', 'bower_components', 'vendor'])
    .pipe($.webserver({
      port: 9000,
      livereload: true,
      proxies: [
        {
          source: '/api', target: 'http://localhost:8888/api'
        }
      ]
    }))
    .on('error', shallowError)
})
```

Prior to learning about webserver being able to proxy I was using Nginx which was working fine.

**Comment by omarmeky** [comment]
@MikaAK I am having this issue, how were you able to resolve it?
