### ISSUE TITLE
You are blacklisted by http://gulpjs.com/plugins/

### ISSUE THREAD

**Issue by zckrs** [schickling/gulp-webserver#65]
https://github.com/gulpjs/plugins/blob/master/src/blackList.json#L236

:cry:

**Comment by LongLiveCHIEF** [comment]
The authors of gulp seem to forget that there is a very good reason for the facade pattern. They blacklist just about every plugin that has that purpose.

**Comment by callumacrae** [comment]
It was blacklisted because gulp plugins are supposed to do stuff with files, and this doesn't. There is no reason for this to be a gulp plugin, and it would work perfectly fine if it were just a module which accepted files paths as input.
