### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by Errvald** [schickling/gulp-webserver#74]
Proxies are not working for me for some reason.

Here's my parameters:
```
var api = {
      port: 3000,
      proxies: [{
        source: '/api',
        target: 'http://localhost:8080/api'
      }]
};

```

```
XMLHttpRequest cannot load http://localhost:8080/api/test. No 'Access-Control-Allow-Origin'...
```

**Comment by eranimo** [comment]
Try adding the Access-Control-Allow-Origin header under options > headers

**Comment by omarmeky** [comment]
Proxies are not working for me as well. The CORS header should not be needed since the server is the one making the cross origin request through the proxy.
