### ISSUE TITLE
How to use middleware?

### ISSUE THREAD

**Issue by joenil** [schickling/gulp-webserver#78]
Please make a code demo, thks

**Comment by animabear** [comment]
You can use middleware like this:
```javascript
middleware: function(req, res, next) {
    // ...
    next();
}
```
For more information you can refer to [https://github.com/senchalabs/connect#use-middleware](https://github.com/senchalabs/connect#use-middleware) . The gulp-webserver uses this.

**Comment by Chalkin** [comment]
Did you manage to get it working?

I tried the following code and my server starts to timeout and sends the "ERR_EMPTY_RESPONSE" error on chrome.

The URL http://backend.api is set up correctly and works fine. API request are coming for example through http://backend.api/api/v1/users with Laravel 5 as API and angularjs as frontend.

Without the middleware part, the webserver works fine and delivers my angularjs page

Nodejs is loading:
"gulp-webserver": "^0.9.1"
"proxy-middleware": "^0.11.1"
"connect-history-api-fallback": "^1.1.0",

```
....
var historyApiFallback  = require('connect-history-api-fallback');
var plugins  = require('gulp-load-plugins')();
...

gulp.task('webserver', function() {
    gulp.src(paths.serverRoot)
        .pipe(plugins.webserver({
            port: 3000,
            middleware: function (req, res, next) {
                return [(function () {
                    var url = require('url');
                    var proxy = require('proxy-middleware');
                    var options = url.parse('http://backend.api/api');
                    options.route = '/api';
                    return proxy(options);
                })(), historyApiFallback];
            }
        }));
});
```

The part inside the 'middleware' is basicly what i used with gulp-connect

I also tried to do it this way, but the 'req.url' does not match the route '/api/users/'

```
middleware: function(req, res, next) {
                if (req.url === '/api') {
                    res.end('http://backend.api/api/');
                } else {
                    next();
                }
            }
```

**Comment by animabear** [comment]
You can print the req.url and check it. My code like this:

```
middleware: function(req, res, next) {
    var urlObj = url.parse(req.url, true),
        method = req.method,
        paramObj = urlObj.query;

    // Custom function to mock data
    mockApi(res, urlObj.pathname, paramObj, next);
}
```

**Comment by s10mcow** [comment]
+1
