### ISSUE TITLE
Severe performance isues

### ISSUE THREAD

**Issue by remojansen** [schickling/gulp-webserver#97]
I'm not sure about how to reproduce the issue but I was working on a project with 3 files (`demo.js`, `demo.html` and `demo.css`) everything was fine until gulp-webserver started to cause some severe performance issues in my machine:

![3](https://cloud.githubusercontent.com/assets/10656223/11273284/588acd50-8eca-11e5-9653-61fed721657a.png)

![2](https://cloud.githubusercontent.com/assets/10656223/11273286/5b22ac5e-8eca-11e5-8f44-d7c625147944.png)

As you can see it the CPU has intervals from < 10% to  > 90%:

![1](https://cloud.githubusercontent.com/assets/10656223/11273339/abf66864-8eca-11e5-887e-0495015cce47.png)

For the moment turning off livereload:

```
gulp.task('serve', function() {
  gulp.src('./')
    .pipe(webserver({
      directoryListing: true,
      open: "http://localhost:8000/index.html",
      livereload: {
        enable: false
      }
    }));
});
```

Helps me to get around it. One of the files (`demo.html`) is a bit large maybe that is the root cause of the problem?

![untitled](https://cloud.githubusercontent.com/assets/10656223/11273472/5544012e-8ecb-11e5-9613-dfa4d6cfcc43.png)

**Comment by yairEO** [comment]
seems like the author has abandoned the project...

**Comment by remojansen** [comment]
Not sure if solved but closing so it is not listed under my issues....
